# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88a363f61bcb071faf4d2478c01657038a487af1dc88b884ce6649a85689d0747aff0999f6060a1f20e80e01f7a3772b7e32e31c9f2652787edef375fa8906d

test:
  secret_key_base: d33408bc2f408c56973a9ea3cbea52c17035a1ff61425c33571136369c2256c502dd027ae4284f95d5df7efccc7093e91e5b212b15d277ee80314d6a2db18efd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
